config/routes.rb
Foodinary::Application.routes.draw do

  resources :restaurants
  resources :reviews

  root "restaurants#index"

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :restaurant
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
  	@restaurants = Restaurant.all
  end

  def new
  	@restaurant = Restaurant.new
  end

  def create
  	@restaurant = Restaurant.new(restaurant_params)
  	@restaurant.save
  	flash[:notice] = "Success: Restaurant Listing Created"
  	redirect_to @restaurant
  end

  def show
  	@restaurant = Restaurant.find(params[:id])
  end

  def edit
  	@restaurant = Restaurant.find(params[:id])
  end

  def update
  	@restaurant = Restaurant.find(params[:id])

  	if @restaurant.update(restaurant_params)
  		flash[:notice] = "Success: Restaurant Information Has Been Updated"
  		redirect_to @restaurant
  	else
  		render 'edit'
  	end
  end

  def destroy
  	@restaurant = Restaurant.find(params[:id])
  	@restaurant.destroy
  	flash[:notice] = "Success: Restaurant Has Been Deleted"
  	redirect_to root_path
  end


  private

  def restaurant_params
  	params.require(:restaurant).permit(:name, :description)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

	def new
		@review = Review.new
	end

	def create
	  	@review = Review.new(review_params)
	  	@review.save
	  	flash[:notice] = "Success: Review Added"
	  	redirect_to root_path
  	end


  private

  def review_params
  	params.require(:review).permit(:review_title, :review_body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Foodinary</title>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,400,300,600,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<header>
<%= link_to 'New Restaurant', new_restaurant_path %>
</header>

<%= yield %>

</body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for @restaurant do |f| %>
  <% if @restaurant.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this from being saved:</h2>
    <ul>
    <% @restaurant.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %><br>
  </p>
 
  <p>
    <%= f.label :description %><br>
	<%= f.text_area :description, :cols => 30, :rows => 10 %><br>
  </p>
 
  <p>
    <%= f.submit @restaurant.new_record? ? "Create" : "Update" %>
  </p>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Edit Restaurant Profile</h1>

<%= render 'form' %>

<%= link_to 'Back', :back %>
<%= link_to 'Home', root_path %>

<footer>
<%= link_to 'Delete Restaurant Profile', restaurant_path(@restaurant),
                    method: :delete, data: { confirm: 'Are you sure?' } %>
</footer>

app/views/restaurants/index.html.erb
<h1>Foodinary</h1>

<container>
	<h3 class="list_title">Reviewed Restaurants</h3>

<% @restaurants.each do |restaurant| %>
	<article>
		<p class="restaurant_name">
			Restaurant name: 
			<a href="<%= restaurant_path(restaurant) %>" class="restaurant_name_link"><%= restaurant.name %></a>
		</p>
		<p class="restaurant_description">
			Description: <%= restaurant.description %>
		</p>
		<p class="avg_rating">
			Rating <%= image_tag("5star.png", :alt => "five stars") %>
		</p>
	<article>
	<br>
<% end %>
</container>

app/views/restaurants/new.html.erb
<h1>Create Restaurant Listing</h1>

<%= render 'form' %>

<%= link_to 'Back', :back %>
<%= link_to 'Home', root_path %>

app/views/restaurants/show.html.erb
<%= link_to 'Home', root_path %> | <%= link_to 'Edit Restaurant Profile', edit_restaurant_path %>
<br><br><br>

<p class="restaurant_name"><%= @restaurant.name %></p>
<p class="restaurant_description"><%= @restaurant.description %></p>


<br><br>
<container>
<%= link_to 'Add Review', new_review_path %>

</container>

app/views/reviews/new.html.erb
<h1>Create Restaurant Review</h1>

<%= form_for @review do |f| %>
  <% if @review.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@review.errors.count, "error") %> prohibited this from being saved:</h2>
    <ul>
    <% @review.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :Title %><br>
    <%= f.text_field :review_title %><br>
  </p>
 
  <p>
    <%= f.label :Review %><br>
	<%= f.text_area :review_body, :cols => 30, :rows => 10 %><br>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>


 <!-- @review.new_record? ? "Create" : "Update" -->